version: "3"

services:
  rt:
    image: netsandbox/request-tracker:4.4
    hostname: rt
    container_name: puppet_rt
    environment:
      RT_WEB_PORT: "34000"
    ports:
      - "34000:34000"
    expose:
      - "34000"

  mysql:
    image: mariadb:10.4.18
    hostname: mysql
    container_name: puppet_mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    build:
      context: .
      dockerfile: ../docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    command: ["slurmdbd"]
    container_name: puppet_slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    build:
      context: .
      dockerfile: ../docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmctld"]
    container_name: puppet_slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "22"
      - "6817"

  c1:
    build:
      context: .
      dockerfile: ../docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmd"]
    privileged: true
    hostname: c1
    container_name: puppet_c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../data:/home/ood/ondemand/data:rw
      - ood_dashboard:/var/www/ood/apps/sys/dashboard
    expose:
      - "22"
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    build:
      context: .
      dockerfile: ../docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmd"]
    hostname: c2
    privileged: true
    container_name: puppet_c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ../data:/home/ood/ondemand/data:rw
      - ood_dashboard:/var/www/ood/apps/sys/dashboard
    expose:
      - "22"
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  ood_dashboard:
