version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    hostname: keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./target/keycloak-radius-spi-jar-with-dependencies.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-radius-spi-jar-with-dependencies.jar
    ports:
      - "8080:8080"
    expose:
      - "8080"

  radius:
    image:  freeradius/freeradius-server:latest
    hostname: radius
    container_name: radius
    volumes:
      - ./raddb/authorize:/etc/raddb/mods-config/files/authorize
      - ./raddb/clients.conf:/etc/raddb/clients.conf
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    expose:
       - "1812"
       - "1813"
    command: ["radiusd", "-X", "-t"]

