version: "3"

services:
  rt:
    image: netsandbox/request-tracker:4.4
    hostname: rt
    container_name: ondemand_rt
    environment:
      RT_WEB_PORT: "34000"
    ports:
      - "34000:34000"
    expose:
      - "34000"

  mysql:
    image: mariadb:10.4.18
    hostname: mysql
    container_name: ondemand_mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  ood:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_ONDEMAND_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    hostname: ood
    container_name: ondemand_ood
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./development/RstudioDev:/var/www/ood/apps/sys/RstudioDev
      - ./development/rdesktop:/var/www/ood/apps/sys/rdesktop
      - ./apps/GenericRD:/var/www/ood/apps/sys/GenericRD
      - ./apps/JBrowse:/var/www/ood/apps/sys/JBrowse
      - ./apps/Jupyter:/var/www/ood/apps/sys/Jupyter
      - ./apps/Matlab:/var/www/ood/apps/sys/Matlab
      - ./apps/OmniSci:/var/www/ood/apps/sys/OmniSci
      - ./apps/Postgres:/var/www/ood/apps/sys/Postgres
      - ./apps/RemoteDesktop:/var/www/ood/apps/sys/RemoteDesktop
      - ./apps/RStudioServer:/var/www/ood/apps/sys/RStudioServer
      - ./apps/SAS:/var/www/ood/apps/sys/SAS
      - ./apps/Stata:/var/www/ood/apps/sys/Stata
      - ./apps/TensorBoard:/var/www/ood/apps/sys/TensorBoard
      - ./apps/Totalview-Desktop:/var/www/ood/apps/sys/Totalview-Desktop
      - ../VERSION:/var/www/ood/apps/sys/dashboard/VERSION
      - ./data:/home/ood/ondemand/data:rw
      - ./application/dashboard:/etc/ood/config/apps/dashboard
      - ./lib/ood_core:/var/www/ood/apps/sys/dashboard/lib/ood_core
      - ./ondemand.d:/etc/ood/config/ondemand.d
      - ./public:/var/www/ood/public
      - ./docker/dev-cluster.yml:/etc/ood/config/clusters.d/dev-cluster.yml
      - ./announcements.d:/etc/ood/config/announcements.d
      - ./apache/timeout.conf:/opt/rh/httpd24/root/etc/httpd/conf.d/timeout.conf
    ports:
      - "33000:443"
    expose:
      - "6817"
      - "8080"
      - "80"
      - "443"
    depends_on:
      - "slurmctld"
    links:
      - "slurmctld"


  slurmdbd:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    command: ["slurmdbd"]
    container_name: ondemand_slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmctld"]
    container_name: ondemand_slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "22"
      - "6817"

  c1:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmd"]
    privileged: true
    hostname: c1
    container_name: ondemand_c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./data:/home/ood/ondemand/data:rw
    expose:
      - "22"
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      args:
        DOCKER_IMAGE: ${SID_SLURM_IMAGE}
        OOD_UID: ${OOD_UID}
        OOD_GID: ${OOD_GID}
    entrypoint: /usr/local/bin/with-ssh.sh
    command: ["slurmd"]
    hostname: c2
    privileged: true
    container_name: ondemand_c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./data:/home/ood/ondemand/data:rw
    expose:
      - "22"
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
