name: automated-tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "build-and-test" ]
    branches: [ canary, stable ]
    types:
      - completed

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Build and test
        working-directory: ./automated-testing
        run: make test