name: dashboard-production-build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag number for release, eg: 0.9.0'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Creates build
        working-directory: ./dashboard
        run: make release
      - name: Commits release
        run: |
          git config --global user.name 'CI Pipeline'
          git config --global user.email 'ci-pipeline@users.noreply.github.com'
          git add ./dashboard/deployment/sid_passenger/files/application -f
          git commit -m "Created release v${{ github.event.inputs.tag }}"
          git push
          git tag -a v${{ github.event.inputs.tag }} -m "Created release v${{ github.event.inputs.tag }}"
          git push --tags
