name: keycloak-spi-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag number for release, eg: 0.9.0'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ./keycloak-radius-spi/maven-local-repo
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Tests
        working-directory: ./keycloak-radius-spi
        run: make build
      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release create v${{ github.event.inputs.tag }} --notes "Release Notes" './keycloak-radius-spi/target/keycloak-radius-spi-jar-with-dependencies.jar'