name: continous-integration

on:
  push:
    branches:
      - canary
      - stable
    paths:
      - 'keycloak-radius-spi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Tests
        working-directory: ./keycloack-radius-spi
        run: make docker-build
